### PR TITLE
Create Release on new tag and add PGN databases as artifacts

### PR DESCRIPTION
**Pull request by aldas**
This is related to https://github.com/canboat/canboat/issues/325

This Github workflow is triggered when new Tag with pattern `v[0-9]+.[0-9]+.[0-9]+` is pushed/created.   As a result https://github.com/softprops/action-gh-release actions will create new Release with that tag name and attach following files as artifacts `docs/canboat.json`, `docs/canboat.xml`, `docs/canboat.xsd`.

Release will look like that:
image

### CODE REVIEW

**Comment by tkurki** [comment]
Nice! 

The update to checkout v3 in ci.yml could be a separate commit, as it is not really a part of this feature.

I think it would be a good idea to sanity check that the versions in .json and .xml files matches the tag to guard against human errors.

**Comment by aldas** [comment]
I think sanity checks should be done for PRs or commits to master. Blocking release page being automatically being updated does not solve the (root) problem - which is commits or PR were untested.

This flow starts when tag is created/pushed. I am not aware if Github workflow supports "pre-tag-hooks" that block creating/pushing tags. Because if this workflow would stop run on problems, this would mean only "release" page is guarded - the problematic Tag still exists and problematic commits still exist in git log/history.

**Comment by tkurki** [comment]
If you by mistake create a tag that does not match the version in the files then you also create an inconsistent release. A check in this workflow would alert you to the mistake and prevent creating the release with inconsistent information, allowing you to take fix things by fixing just one mistake (remove the bad tag) and not two (bad tag and bad release).

You can't check if the version in the files is the same as the tag in master nor in PRs, because neither of them are the tag. A pre push hook that runs on tags would probably work.

**Comment by aldas** [comment]
These are good things but are not necessary for this PR as it is not meant to fix quality assurance problems or complicate current developer way of working. 

This is a small incremental step in forward - it solves one specific thing without affecting anything else. If additional/different quality gates or changes in development process are needed these could be added in further PRs as involved people see it fit.

**Comment by keesverruijt** [comment]
I like this (small but significant step)!

> I am not aware if Github workflow supports "pre-tag-hooks" that block creating/pushing tags. 
I don't think so, as @tkurki says a `git commit` with a version number in a file is independent of pushing the tags.

> Because if this workflow would stop run on problems, this would mean only "release" page is guarded - the problematic Tag still exists and problematic commits still exist in git log/history.

I agree with @tkurki : anything automated should check for all it can, and this would prevent silly mistakes -- even if it is only the release page. I still think it is worthwhile.

A good next step could be: only push to [github.io](https://canboat.github.io/canboat/canboat.xml) when a release is made, so that intermediate commits aren't pushed all the time.

**Comment by aldas** [comment]
At the current development process maturity level, schema version is probably one of the smallest things to care in relation to schema files. 

There have been changes to schema - to struct fields or classifier values etc so you always need to check in your own library/application if can "support" that schema at all. So you pretty much are forced to lock your library/application to one fixed version that you have tested. In that case whatever number is in xml/json does not matter at all. As currently no semantic versioning actually exists or is being practiced - means that major/minor/patch parts in schema version are useless. 

Some example: recently `STRING_VAR` field type was removed, `INDIRECT_LOOKUP` type was added - any change to field type is more than likely breaking change and must trigger major version bump. NB: Schema version and Canboat version is different.

Unless strict semantic versioning is being done and CI flow to detect these changes are in place - checking version string when tag is pushed makes little difference.  

Semantic versioning is hard to achieve as it very hard to check with static analysis - it is more to do with developer own discipline and maybe review process. 

Allowing downstream users to pin to fixed version - gives them some guarantees that only verified/test (by themselves) version will be used/downloaded.

**Comment by tkurki** [comment]
Did not want to start a debate, merely tried to suggest something that I thought would be a good idea and very little more work.

**Comment by tkurki** [comment]
Ok, one more comment, sorry 😄 

Afai understand if this PR is merged one is supposed to git tag versions and once pushed that will create automatically Github Releases containing the artifacts. I think that is a great idea.

My concern is that if there is no sanity check that ensures that the artifacts have the same version number as the release merging this PR creates a mechanism where it is pretty easy to create inconsistent releases. This is directly related to the mechanism introduced in this PR, not a separate issue.

Even today the situation is that if I download release artifacts for [release v1.3.0](https://github.com/canboat/canboat/releases/tag/v1.3.0) I get files where it says `#define VERSION "1.2.1"`.  Errors like this are easy to do when there are manual steps. Been there, done that, several times.

How versioning happens is a separate issue, but ensuring that tags & artifact contents match is valuable in its own right.


But at the end of the day I am still 👍 for merging this and starting using GH Releases, check or no check.

**Comment by aldas** [comment]
I have added some checks to compare `common/version.h` value with artifacts.

I do no think this is eloquent solution because only thing this does is that Release page will not be updated. The "error flow" is limited in this situation.

The TAG still exists so that buggy release *actually* exists.  Github releases are just cosmetic Github specific feature that is built on Git tags and help you download repository artifacts from web (instead of cloning the repo etc).

**Pull request merged**
