### PR TITLE
Added 3 missing device functions

### PR DESCRIPTION
**Pull request by mbj4668**
The PR adds 3 missing device functions, and a sample file.
I am not sure about the correct device function strings; they are not from any official documentation.

### CODE REVIEW

**Comment by sbender9** [comment]
133 is N2K to Serial Gateway

**Comment by sbender9** [comment]
And change 137 to "NMEA 2000 Wireless Gateway"

**Comment by sbender9** [comment]
Haha! And while you are at it, 136 is "NMEA Network Gateway"

**Comment by mbj4668** [comment]
Ok.  Not "NMEA 2000 Network Gateway"?

... do you know what kind of device that is?

Den fre 28 apr. 2023 kl 15:04 skrev Scott Bender ***@***.***>:

**Comment by sbender9** [comment]
No. Not 2000. It is for OneNet gateways.

**Comment by mbj4668** [comment]
This PR is ready to be merged

**Comment by mbj4668** [comment]
@sbender9 do you know what DeviceClass=110, DeviceFunction=130 is?

**Comment by sbender9** [comment]
Class 110 is "Human Interface Device"

130 = "Button Interface"
135 = "Switch Interface"
140 = "Analog Interface"

**Comment by mbj4668** [comment]
Thanks!

**Pull request merged**
